<?php

const USERNAME = 'dyndns';
const PASSWORD = 'StrongP@SSwo$d';

const PROTOCOL = 'http';
const PORT = '80';
const PATH = '';

const USE_IP6 = false;
const USE_PROXY = true;

// a unique key that identifies this application - DO NOT LEAVE THIS EMPTY!
const API_KEY = 'nSeaKeS7n3A2GEK6GGz5UcaceE6NvJnz';

/*
how unique is each URL that is generated by this proxy app?
0 - no encoding of any sort. People can link to proxy pages directly: ?q=http://www.yahoo.com
1 - Base64 encoding only, people can hotlink to your proxy
2 - unique to the IP address that generated it. A person that generated that URL, can bookmark it and visit it and any point
3 - unique to that session and IP address - URL no longer valid anywhere when that browser session that generated it ends
*/
const URL_MODE = 0;

// additional curl options to go with each request
const CURL = [
    CURLOPT_FOLLOWLOCATION => false,
//    CURLOPT_HEADER => true,
//    CURLOPT_RETURNTRANSFER => true,
//    CURLINFO_HEADER_OUT => true,
//    CURLOPT_POST => true
];
